Tooltip
js-tasks-ru/htmlcss-20210513_deman4ig pull request #10
Opened 2021-06-02 12:50 UTC by Deman4ig

2021-06-02 12:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-02 20:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-08 13:12 UTC, GSemikozov requested changes

2021-06-08 13:12 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
в предыдущем ПР писал что общие стили или стили которые не относятся к стилям блока стоит выносить

2021-06-10 21:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-11 08:43 UTC, GSemikozov approved these changes

2021-06-11 08:44 UTC, merged