Add solution for lesson 05: toggler
js-tasks-ru/htmlcss-20210513_deman4ig pull request #20
Opened 2021-06-11 20:45 UTC by Deman4ig

2021-06-11 20:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-13 19:17 UTC, GSemikozov requested changes

2021-06-13 19:17 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    display: flex;
писал в предыдущем ПР-е)

2021-06-13 19:17 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    transform: translateX(97%);
тут наверное чтобы избежать возможных коллизий лучше задать сразу в пикселях - все равно другие значения у нас тоже заданы в пикселях

2021-06-14 10:17 UTC, Deman4ig commented on 07-lection5/03-toggler/toggler.css
> +    display: flex;
Поправил!

2021-06-14 10:17 UTC, Deman4ig commented on 07-lection5/03-toggler/toggler.css
> +    transform: translateX(97%);
Мда! Интересный элемент...

2021-06-15 13:07 UTC, GSemikozov approved these changes

2021-06-15 13:07 UTC, merged