Complete modal component
js-tasks-ru/htmlcss-20210513_deman4ig pull request #24
Opened 2021-06-21 01:14 UTC by Deman4ig

Replace modal sample content with a form

2021-06-21 09:13 UTC, GSemikozov requested changes

2021-06-21 09:13 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +    <svg class='modal__close-icon'
чтобы следовать правилам семантической верстки, я бы советовал обернуть в button и закрывать по нажатию на кнопку а не на иконку

2021-06-21 21:01 UTC, Deman4ig commented on 05-lection3/02-modal/index.html
> +    <svg class='modal__close-icon'
прислушался:)

2021-06-22 12:13 UTC, GSemikozov approved these changes

2021-06-22 12:13 UTC, merged