Buttons
js-tasks-ru/htmlcss-20210513_deman4ig pull request #3
Opened 2021-05-22 19:27 UTC by Deman4ig

2021-05-22 19:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-28 15:36 UTC, GSemikozov requested changes

2021-05-28 15:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:hover:enabled {
:enabled указывать не обязательно

2021-05-28 15:36 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
еще, чтобы запретить нажимать на кнопку, нужно добавить `pointer-events: none`

2021-05-30 19:01 UTC, GSemikozov approved these changes

2021-05-30 19:01 UTC, merged