Histogram
js-tasks-ru/htmlcss-20210513_deman4ig pull request #6
Opened 2021-05-25 11:33 UTC by Deman4ig

2021-05-25 11:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-28 15:43 UTC, GSemikozov requested changes

2021-05-28 15:43 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-left: 1em;
в данном случае это все-таки скорее внешний отступ - margin-left

2021-05-28 15:43 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 2.5em;
можно и через паддинг, но - все-таки когда мы хотим добавить отступ от другого элемента - это внешний отступ margin, когда просто внутри добавляем "поля" - padding

2021-05-29 15:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-29 16:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-29 16:04 UTC, Deman4ig commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 2.5em;
думаю что понял:) посмотрим в других коммитах

2021-05-29 16:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 17:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 18:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-30 19:03 UTC, GSemikozov approved these changes

2021-05-30 19:03 UTC, merged