Components layout
js-tasks-ru/htmlcss-20210513_deman4ig pull request #7
Opened 2021-05-31 21:38 UTC by Deman4ig

2021-05-31 21:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-01 10:28 UTC, GSemikozov requested changes

2021-06-01 10:28 UTC, GSemikozov commented on index.html
> +          <p class='preview__header'>Custom form elements</p>
странно что хедер идет за боди... тогда может footer?

2021-06-01 10:28 UTC, GSemikozov commented on components/preview/preview.css
> +.preview {
в примере на лекции это был компонент-контейнер, а поскольку у нас уже есть main__inner, этоьт компонент я бы посоветовал переименовать в .card -  так будет все-таки логичнее. Но - это не обязательно.

2021-06-03 10:54 UTC, Deman4ig commented on index.html
> +          <p class='preview__header'>Custom form elements</p>
действительно странно:)

2021-06-03 10:54 UTC, Deman4ig commented on components/preview/preview.css
> +.preview {
согласен - card звучит более подходящим

2021-06-08 12:59 UTC, GSemikozov requested changes

2021-06-08 12:59 UTC, GSemikozov commented on components/components-grid/components-grid.css
> +    flex-wrap: wrap;
здесь, по идее, еще нужно добавить отрицательные марджины margin: 0 -15px (чтобы растянуть контейнер на 15 пикселей крайних блоков слева и справа)

2021-06-08 12:59 UTC, GSemikozov commented on components/navigation/navigation.css
> +    display: flex;
поскольку ссылка должна бы растягиваться по ширине внутреннего содержимого (текста), а не родителя - все-таки предпочтительнее использовать inline-flex

2021-06-08 12:59 UTC, GSemikozov commented on components/components-grid/components-grid.css
> +    flex-wrap: wrap;
то есть правильнее это сделать здесь, а не на уровне main__inner

2021-06-08 20:38 UTC, Deman4ig commented on components/navigation/navigation.css
> +    display: flex;
у меня эта фигня осталась в коде случайно - т.к. сначала сделал через ul > li > a, а потом подумал что наверное нет смысла в такой структуре и переделал на nav > a.

так что убрал вообще display: flex

2021-06-08 20:41 UTC, Deman4ig commented on components/components-grid/components-grid.css
> +    flex-wrap: wrap;
согласен!

2021-06-09 07:36 UTC, GSemikozov submitted a review, later dismissed

2021-06-09 07:36 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-06-10 08:21 UTC, GSemikozov approved these changes

2021-06-10 08:21 UTC, merged